### ISSUE TITLE
No webcam feed

### ISSUE THREAD

**Issue by nmaggioni** [nairbspace/octoandroid#3]
I can't get the webcam to work in the app - it works fine in OctoPrint and in its plugins.
As per the official documentation I have the feed running on port 8080, with query `/?action=stream`.
When interrogated directly via the browser (`http://myOctoPrintHost:8080/?action=stream`) it works fine as well.

Both the default setting and `:8080/?action=stream` for the webcam's path/query in the app lead to just a black screen in the webcam section. Am I missing something?

The rest of the app is awesome! Keep up the good work :)

**Comment by nairbspace** [comment]
Niccolò,

Have you tried `/webcam/?action=stream`? The webcam has always been iffy at best which is why it is still experimental. The code is from a 3rd party library, but I've never been happy with the way the code was implemented. I haven't worked on this app for over a month due to job hunting/relocating, but good news is that I've just finished up so I can get back to doing the fun stuff again (working on this app). Sorry again for the delayed response.

**Comment by nmaggioni** [comment]
No worries, a maintainer of OSS projects should never be blamed for delayed responses :)

I tried that as well (it is the default setting, right?), but to no avail. **But I'm not running OctoPi, just a standard installation of OctoPrint on Debian.**
[As per the official documentation](https://github.com/foosel/OctoPrint/wiki/Setup-on-a-Raspberry-Pi-running-Raspbian#webcam) the webcam answers at `:8080/?action=stream` indeed. I guess there are no other big differences to OctoPi, since the image is shown fine in the _Control_ tab and timelapses work as well.

Good luck on your stuff!
